---
kind: pipeline
type: docker
name: default

steps:
- name: deploy
  image: nytimes/drone-gae:latest
  when:
    branch:
    - master
    event:
    - push
  settings:
    action: deploy
    project: jprbnsn
    version: "${DRONE_COMMIT}"
    max_versions: 2
  environment:
    GAE_CREDENTIALS:
      from_secret: google_credentials

- name: dispatch:
  image: nytimes/drone-gae
  when:
    branch:
    - master
    event:
    - push
  settings:
    action: update_dispatch
    project: jprbnsn
    dispatch_file: dispatch.yaml
    version: "${DRONE_COMMIT}"
  environment:
    GAE_CREDENTIALS:
      from_secret: google_credentials

