pipeline:
  deploy:
    image: nytimes/drone-gae:latest
    action: deploy
    project: jprbnsn
    version: "${DRONE_COMMIT}"
    max_versions: 2
    secrets:
      - source: google_credentials
        target: GAE_CREDENTIALS
    when:
      branch: [master]
      event: push

  dispatch:
    environment:
      - GOPATH=/drone
    image: nytimes/drone-gae
    action: update_dispatch
    project: jprbnsn
    dispatch_file: dispatch.yaml
    version: "${DRONE_COMMIT}"
    secrets:
      - source: google_credentials
        target: gae_credentials
    when:
      event: push
      branch: master
